[package]
name = "iwdrs"
version = "0.1.6"
edition = "2024"
license = "MIT"
description = "Rust cratte for iwd"
readme = "Readme.md"
homepage = "https://github.com/pythops/iwdrs"
repository = "https://github.com/pythops/iwdrs"

[dependencies]
zbus = "5"
zvariant = "5"
anyhow = "1"
uuid = { version = "1", features = ["v4"] }
