---
on:
  push:
    branches:
      - "*"
name: CI
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy rustfmt

      - name: Lint
        run: |
          cargo clippy --workspace --all-features -- -D warnings
          cargo fmt --all -- --check

      - name: Build
        run: cargo build
